name: Accessibility
on:
  pull_request:
    types: opened
  issues:
    types: opened
  issue_comment:
    types: created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - name: Install espeak
        run: sudo apt-get install espeak
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
